package com.sanchr.app.smoke

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive

/**
 * One known-answer vector from `oprf_vectors.json`, generated by the backend's
 * `cargo run -p sanchr-psi --example oprf_vectors`. This copy must stay
 * byte-identical to `backend/crates/sanchr-psi/testdata/` and be regenerated
 * together with the vendored `libsanchr_psi_jni.so` — they describe the same
 * protocol version.
 */
class OprfVector(
    val phone: String,
    val blindingScalar: ByteArray,
    val evaluated: ByteArray,
    val setElement: ByteArray,
)

fun parseOprfVectors(json: String): List<OprfVector> =
    Json.parseToJsonElement(json).jsonObject["vectors"]!!.jsonArray.map { v ->
        val o = v.jsonObject
        OprfVector(
            phone = o["phone"]!!.jsonPrimitive.content,
            blindingScalar = o["blinding_scalar_hex"]!!.jsonPrimitive.content.hexToBytes(),
            evaluated = o["evaluated_hex"]!!.jsonPrimitive.content.hexToBytes(),
            setElement = o["set_element_hex"]!!.jsonPrimitive.content.hexToBytes(),
        )
    }

private fun String.hexToBytes(): ByteArray = chunked(2).map { it.toInt(16).toByte() }.toByteArray()
